service: movie-api
runtime: python27
api_version: 1
threadsafe: true
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

handlers:
- url: /.*
  script: run.app

env_variables:
  APP_ENV: 'google-cloud'
